global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Agrupamos las apps para una gestión de etiquetas más limpia
  - job_name: "fastapi-apps"
    scrape_interval: 5s
    # Habilitamos el almacenamiento de ejemplares para saltar de métrica a traza
    enable_protobuf_negotiation: true 
    static_configs:
      - targets: ["app-a:8000", "app-b:8000", "app-c:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: "instance"
      - source_labels: [__address__]
        regex: "app-(.*):8000"
        target_label: "app_name"
        replacement: "app-$1"

storage:
  tsdb:
    out_of_order_time_window: 1m

